// GENERATED CODE - DO NOT MODIFY BY HAND
// ignore_for_file: type=lint, implicit_dynamic_list_literal, implicit_dynamic_map_literal, inference_failure_on_collection_literal

import 'package:mason/mason.dart';

final createProjectBundle = MasonBundle.fromJson(<String, dynamic>{
  "files": [
    {"path": ".env", "data": "", "type": "text"},
    {
      "path": ".gitignore",
      "data": "LmVudi5wcml2YXRlCi52ZW52Lwo=",
      "type": "text"
    },
    {
      "path": ".vscode/launch.json",
      "data":
          "ewogICAgLy8gVXNlIEludGVsbGlTZW5zZSB0byBsZWFybiBhYm91dCBwb3NzaWJsZSBhdHRyaWJ1dGVzLgogICAgLy8gSG92ZXIgdG8gdmlldyBkZXNjcmlwdGlvbnMgb2YgZXhpc3RpbmcgYXR0cmlidXRlcy4KICAgIC8vIEZvciBtb3JlIGluZm9ybWF0aW9uLCB2aXNpdDogaHR0cHM6Ly9nby5taWNyb3NvZnQuY29tL2Z3bGluay8/bGlua2lkPTgzMDM4NwogICAgInZlcnNpb24iOiAiMC4yLjAiLAogICAgImNvbmZpZ3VyYXRpb25zIjogW10KfQ==",
      "type": "text"
    },
    {
      "path": ".vscode/settings.json",
      "data":
          "ewogICAgImFuc2libGUucHl0aG9uLmludGVycHJldGVyUGF0aCI6ICIvdXNyL2Jpbi9weXRob24zIiwKICAgICJkYXJ0LmZsdXR0ZXJTZGtQYXRoIjogIiR7ZW52OkhPTUV9Ly5mdm0vdmVyc2lvbnMvMy4yNC4zIiwKICAgICJnaXQuYXV0b1JlcG9zaXRvcnlEZXRlY3Rpb24iOiAic3ViRm9sZGVycyIsCiAgICAiZ2l0LnJlcG9zaXRvcnlTY2FuTWF4RGVwdGgiOiAzLAogICAgImdpdC5pZ25vcmVMaW1pdFdhcm5pbmciOiB0cnVlCn0K",
      "type": "text"
    },
    {
      "path": ".vsls.json",
      "data":
          "ewogICAgIiRzY2hlbWEiOiAiaHR0cDovL2pzb24uc2NoZW1hc3RvcmUub3JnL3ZzbHMiLAogICAgImdpdGlnbm9yZSI6Im5vbmUiLAogICAgImV4Y2x1ZGVGaWxlcyI6WwogICAgICAgICIqLnAxMiIsCiAgICAgICAgIiouY2VyIiwKICAgICAgICAidG9rZW4iLAogICAgICAgICIuZ2l0aWdub3JlIgogICAgXSwKICAgICJoaWRlRmlsZXMiOiBbCiAgICAgICAgImJpbiIsCiAgICAgICAgIm9iaiIKICAgIF0KfQ==",
      "type": "text"
    },
    {
      "path": ".yade/ascii-art.txt",
      "data":
          "X18gIF9fX19fICAgIF9fX18gIF9fX19fXwpcIFwvIC8gICB8ICAvIF9fIFwvIF9fX18vCiBcICAvIC98IHwgLyAvIC8gLyBfXy8gICAKIC8gLyBfX18gfC8gL18vIC8gL19fXyAgIAovXy9fLyAgfF8vX19fX18vX19fX18vICAgCgp7e3Byb2plY3ROYW1lLnVwcGVyQ2FzZSgpfX0gUHJvamVjdCBERVYgRW52aXJvbm1lbnQ=",
      "type": "text"
    },
    {
      "path": ".yade/set-env.sh",
      "data":
          "IyEvdXNyL2Jpbi9lbnYgYmFzaApjbGVhcgoKZXhwb3J0IFlBREVfUFJPSkVDVF9JRD17e3Byb2plY3ROYW1lLmxvd2VyQ2FzZSgpfX0KZXhwb3J0IFlBREVfUFJPSkVDVF9IT01FPSR7SE9NRX0vcHJvamVjdHMvJHtZQURFX1BST0pFQ1RfSUR9LXlhZGUKZXhwb3J0IFlBREVfUFJPSkVDVF9DT05GPSR7WUFERV9QUk9KRUNUX0hPTUV9L2NvbmYKZXhwb3J0IFlBREVfUFJPSkVDVF9TUkM9JHtZQURFX1BST0pFQ1RfSE9NRX0vc3JjCmV4cG9ydCBZQURFX1BST0pFQ1RfRE9DPSR7WUFERV9QUk9KRUNUX0hPTUV9L2RvYwpleHBvcnQgWUFERV9QUk9KRUNUX1NPRlRXQVJFPSR7WUFERV9QUk9KRUNUX0hPTUV9L3NvZnR3YXJlCgpjYXQgJHtZQURFX1BST0pFQ1RfSE9NRX0vLnlhZGUvYXNjaWktYXJ0LnR4dAoKIyBBa3RpdmllcnQgZGllIG51bGxnbG9iLU9wdGlvbgpzaG9wdCAtcyBudWxsZ2xvYgoKZWNobyAiIgplY2hvICJTb3VyY2luZyBsb2NhbCBlbnYgZmlsZXM6Igpmb3IgZiBpbiAke1lBREVfUFJPSkVDVF9IT01FfS8uZW52KiA7IGRvCiAgZWNobyAiIHwtPiAkZi4uLiIKICAuICRmCmRvbmUKCmlmIFsgLWQgIiRZQURFX1BST0pFQ1RfU09GVFdBUkUiIF07IHRoZW4KICBlY2hvICJTb3VyY2luZyBzb2Z0d2FyZSBzZXQtZW52IGZpbGVzOiIKICBmb3IgZiBpbiAke1lBREVfUFJPSkVDVF9TT0ZUV0FSRX0vc2V0LWVudi0qLnNoIDsgZG8KICAgIGVjaG8gIiB8LT4gJGYuLi4iCiAgICAuICRmCiAgZG9uZQpmaQoKIyBlY2hvICJTb3VyY2luZyBzZXQtZW52LSogZmlsZXM6IgojIGZvciBmIGluICR7WUFERV9QUk9KRUNUX0hPTUV9L3NldC1lbnYtKi5zaCA7IGRvCiMgICBlY2hvICIgfC0+ICRmLi4uIgojICAgLiAkZgojIGRvbmUKCmlmIFtbICIkT1NUWVBFIiA9PSAibGludXgtZ251IiogXV07IHRoZW4KICB0ZXN0IC1mICR7WUFERV9QUk9KRUNUX0hPTUV9L3NldC1lbnYtbGludXguc2ggJiYgc291cmNlICR7WUFERV9QUk9KRUNUX0hPTUV9L3NldC1lbnYtbGludXguc2gKZWxpZiBbWyAiJE9TVFlQRSIgPT0gImRhcndpbiIqIF1dOyB0aGVuCiAgdGVzdCAtZiAke1lBREVfUFJPSkVDVF9IT01FfS9zZXQtZW52LWRhcndpbi5zaCAmJiBzb3VyY2UgJHtZQURFX1BST0pFQ1RfSE9NRX0vc2V0LWVudi1kYXJ3aW4uc2gKZmkKCmV4cG9ydCBQQVRIPSIke1lBREVfUFJPSkVDVF9IT01FfS9iaW46JHtIT01FfS8ubG9jYWwvYmluOiR7UEFUSH0iCg==",
      "type": "text"
    },
    {
      "path": "conf/yade.yml",
      "data":
          "cHJvamVjdDoKICBuYW1lOiB7e3Byb2plY3ROYW1lLmxvd2VyQ2FzZSgpfX0KICByZXBvc2l0b3JpZXM6CiAgICAjIC0gdXJsOiBnaXRAZ2l0bGFiLm1nbS5jYXMua3ZuYncubmV0OmNhcy9jb21wb25lbnRzL3RlcnJhZm9ybS9tb2R1bGUtY2x1c3Rlci1jb250cm9sLXBsYW5lLmdpdAogICAgIyAgIHBhdGg6IHRlcnJhZm9ybS9tb2R1bGUtY2x1c3Rlci1jb250cm9sLXBsYW5lCiAgICAjIC0gdXJsOiBnaXRAZ2l0bGFiLm1nbS5jYXMua3ZuYncubmV0OmNhcy9jb21wb25lbnRzL3RlcnJhZm9ybS9tb2R1bGUtY2x1c3Rlci13b3JrZXItZ3JvdXAuZ2l0CiAgICAjICAgcGF0aDogdGVycmFmb3JtL21vZHVsZS1jbHVzdGVyLXdvcmtlci1ncm91cA==",
      "type": "text"
    },
    {
      "path": "console",
      "data":
          "IyEvdXNyL2Jpbi9lbnYgYmFzaAoKWyAhIC1mIC55YWRlL3NldC1lbnYuc2ggXSAmJiBlY2hvICJzZXQtZW52LnNoIGRvZXMgbm90IGV4aXN0LiBNYWtlIHN1cmUgeW91IGFyZSBydW5uaW5nIHRoZSBjb21tYW5kIGZyb20gYSBwcm9qZWN0IGhvbWUgZGlyZWN0b3J5IiAmJiBleGl0IDEKCnNvdXJjZSAueWFkZS9zZXQtZW52LnNoCgpjZCAkWUFERV9QUk9KRUNUX0hPTUUKCmlmIFtbICIkMSIgPT0gIi12IiBdXTsgdGhlbgogICAgZWNobyAiIgogICAgZWNobyAiWUFERV9QUk9KRUNUX0lEICAgICAgOiAkWUFERV9QUk9KRUNUX0lEIgogICAgZWNobyAiWUFERV9QUk9KRUNUX0hPTUUgICAgOiAkWUFERV9QUk9KRUNUX0hPTUUiCiAgICBlY2hvICJZQURFX1BST0pFQ1RfQ09ORiAgICA6ICRZQURFX1BST0pFQ1RfQ09ORiIKICAgIGVjaG8gIllBREVfUFJPSkVDVF9TUkMgICAgIDogJFlBREVfUFJPSkVDVF9TUkMiCiAgICBlY2hvICJZQURFX1BST0pFQ1RfRE9DICAgICA6ICRZQURFX1BST0pFQ1RfRE9DIgogICAgZWNobyAiWUFERV9QUk9KRUNUX1NPRlRXQVJFOiAkWUFERV9QUk9KRUNUX1NPRlRXQVJFIgpmaQo=",
      "type": "text"
    },
    {
      "path": "doctor.sh",
      "data":
          "IyEvYmluL2Jhc2gKCiMgTmFtZSBkZXMgenUgcHLDvGZlbmRlbiBEYXRlaQpmaWxlPSIuZW52LnByaXZhdGUiCgpjbGVhcgoKY2F0IDw8ICJFT0YiCl9fICBfX19fXyAgICBfX19fICBfX19fX18gICBfX19fICAgICAgICAgICAgIF9fICAgICAgICAgICAgClwgXC8gLyAgIHwgIC8gX18gXC8gX19fXy8gIC8gX18gXF9fX18gIF9fX19fLyAvX19fX18gIF9fX19fCiBcICAvIC98IHwgLyAvIC8gLyBfXy8gICAgLyAvIC8gLyBfXyBcLyBfX18vIF9fLyBfXyBcLyBfX18vCiAvIC8gX19fIHwvIC9fLyAvIC9fX18gICAvIC9fLyAvIC9fLyAvIC9fXy8gL18vIC9fLyAvIC8gICAgCi9fL18vICB8Xy9fX19fXy9fX19fXy8gIC9fX19fXy9cX19fXy9cX19fL1xfXy9cX19fXy9fLyAgICAgCgpDaGVja2luZyBQcmUtY29uZGl0aW9ucyBmb3Ige3tvcmdhbml6YXRpb24udXBwZXJDYXNlKCl9fSB7e2FwcGxpY2F0aW9uTmFtZS51cHBlckNhc2UoKX19IHt7ZW52aXJvbm1lbnQudXBwZXJDYXNlKCl9fQoKRU9GCgojIMOcYmVycHLDvGZlbiwgb2IgZGllIERhdGVpIGV4aXN0aWVydAppZiBbWyAtZiAiJGZpbGUiIF1dOyB0aGVuCiAgICBlY2hvICLinJQgVGhlIGZpbGUgJyRmaWxlJyBleGlzdHMuIgogICAgCiAgICAjIMOcYmVycHLDvGZlbiwgb2IgZGllIERhdGVpIGRpZSBaZWljaGVua2V0dGUgPHNlcnZlcj46PHBvcnQ+IGVudGjDpGx0CiAgICBpZiBncmVwIC1xICI8c2VydmVyPjo8cG9ydD4iICIkZmlsZSI7IHRoZW4KICAgICAgICBlY2hvICIiCiAgICAgICAgZWNobyAi4pqgIEVycm9yOiIKICAgICAgICBlY2hvICJUaGUgZmlsZSAnJGZpbGUnIHN0aWxsIGNvbnRhaW5zIHRoZSBwbGFjZWhvbGRlciAnPHNlcnZlcj46PHBvcnQ+Jy4iCiAgICAgICAgZWNobyAiUGxlYXNlIHJlcGxhY2UgdGhpcyB2YWx1ZSB3aXRoIGEgdmFsaWQgVmF1bHQgaG9zdCBhbmQgcG9ydC4iCiAgICAgICAgZWNobyAiIgogICAgICAgIGV4aXQgMQogICAgZmkKCiAgICAjIMOcYmVycHLDvGZlbiwgb2IgZGllIERhdGVpIGRpZSBaZWljaGVua2V0dGUgPHZhdWx0X3Rva2VuPiBlbnRow6RsdAogICAgaWYgZ3JlcCAtcSAiPHZhdWx0X3Rva2VuPiIgIiRmaWxlIjsgdGhlbgogICAgICAgIGVjaG8gIiIKICAgICAgICBlY2hvICLimqAgRXJyb3I6IgogICAgICAgIGVjaG8gIlRoZSBmaWxlICckZmlsZScgc3RpbGwgY29udGFpbnMgdGhlIHBsYWNlaG9sZGVyICc8dmF1bHRfdG9rZW4+Jy4iCiAgICAgICAgZWNobyAiUGxlYXNlIHJlcGxhY2UgdGhpcyB2YWx1ZSB3aXRoIGEgdmFsaWQgVmF1bHQgdG9rZW4uIgogICAgICAgIGVjaG8gIiIKICAgICAgICBleGl0IDEKICAgIGZpCgogICAgZWNobyAi4pyUIFRoZSBwbGFjZWhvbGRlcnMgaW4gdGhlIGZpbGUgJyRmaWxlJyBoYXZlIGJlZW4gcmVwbGFjZWQuIgplbHNlCiAgICBlY2hvICIiCiAgICBlY2hvICLimqAgRXJyb3I6IgogICAgZWNobyAiVGhlIGZpbGUgJyRmaWxlJyBkb2VzIG5vdCBleGlzdCBpbiB0aGUgY3VycmVudCBkaXJlY3RvcnkuIgogICAgZWNobyAiTWFrZSBhIGNvcHkgb2YgdGhlIHRlbXBsYXRlIC5lbnYucHJpdmF0ZS5leGFtcGxlIGFuZCByZXBsYWNlIHRoZSBwbGFjZWhvbGRlcnMgd2l0aCB0aGUgY29ycmVzcG9uZGluZyB2YWx1ZXMuIgogICAgZWNobyAiIgogICAgZXhpdCAxCmZpCgplY2hvICIiCmVjaG8gIllvdSBjYW4gbm93IHN0YXJ0IG9uZSBvZiB0aGUgZW52aXJvbm1lbnRzLiBFeGFtcGxlOiIKZWNobyAiIgplY2hvICIgIHRhc2sgbWF0cml4Omluc3RhbGw6c2JveCIKZWNobyAiIgoKZXhpdCAw",
      "type": "text"
    },
    {
      "path": "README.md",
      "data":
          "IyB7e2Vudmlyb25tZW50LnVwcGVyQ2FzZSgpfX0gUHJvamVjdCByZXBvc2l0b3J5IGdlbmVyYXRlZCB3aXRoIHlhZGUK",
      "type": "text"
    },
    {
      "path": "software/.gitignore",
      "data":
          "IyBJZ25vcmllcmUgYWxsZSBEYXRlaWVuIHVuZCBWZXJ6ZWljaG5pc3NlCioKCiMgQXVzbmFobWVuIGbDvHIgdmVyc3RlY2t0ZSBWZXJ6ZWljaG5pc3NlICh6LkIuIC5naXRpZ25vcmUgc2VsYnN0KQohLmdpdGlnbm9yZQ==",
      "type": "text"
    },
    {
      "path": "Taskfile.yml",
      "data":
          "IyBodHRwczovL3Rhc2tmaWxlLmRldgoKdmVyc2lvbjogJzMnCgpkb3RlbnY6IFsnLmVudicsICcuZW52LnByaXZhdGUnXQoKc2lsZW50OiB0cnVlCgojIGluY2x1ZGVzOgojICAgbGliczoKIyAgICAgdGFza2ZpbGU6IC50YXNrZmlsZS9JbmNsdWRlZC55bWwKIyAgICAgZmxhdHRlbjogdHJ1ZQojICAgICBpbnRlcm5hbDogdHJ1ZQoKdGFza3M6CiAgZGVmYXVsdDoKICAgIGNtZHM6IAogICAgICAtIGVjaG8gIlRPRE8gSW1wbGVtZW50IHRoZSBjcmVhdGVfY2x1c3Rlcl92bXMgdGFzayIK",
      "type": "text"
    }
  ],
  "hooks": [],
  "name": "create_project",
  "description": "A YADE Infrastructure As Code template",
  "version": "0.1.0+1",
  "environment": {"mason": ">=0.1.0-dev <0.1.0"},
  "readme": {
    "path": "README.md",
    "data":
        "IyBDcmVhdGUgUHJvamVjdCBFbnZpcm9ubWVudAoKWyFbUG93ZXJlZCBieSBNYXNvbl0oaHR0cHM6Ly9pbWcuc2hpZWxkcy5pby9lbmRwb2ludD91cmw9aHR0cHMlM0ElMkYlMkZ0aW55dXJsLmNvbSUyRm1hc29uLWJhZGdlKV0oaHR0cHM6Ly9naXRodWIuY29tL2ZlbGFuZ2VsL21hc29uKQoKQSBCcmljayB0byBjcmVhdGUgYSBwcm9qZWN0IGVudmlyb25tZW50CgpfR2VuZXJhdGVkIGJ5IFttYXNvbl1bMV0g8J+nsV8KClsxXTogaHR0cHM6Ly9naXRodWIuY29tL2ZlbGFuZ2VsL21hc29uCg==",
    "type": "text"
  },
  "changelog": {
    "path": "CHANGELOG.md",
    "data": "IyAwLjEuMCsxCg==",
    "type": "text"
  },
  "license": {
    "path": "LICENSE",
    "data":
        "TUlUIExpY2Vuc2UKCkNvcHlyaWdodCAoYykgMjAyMiBWZXJ5IEdvb2QgVmVudHVyZXMKClBlcm1pc3Npb24gaXMgaGVyZWJ5IGdyYW50ZWQsIGZyZWUgb2YgY2hhcmdlLCB0byBhbnkgcGVyc29uIG9idGFpbmluZyBhIGNvcHkKb2YgdGhpcyBzb2Z0d2FyZSBhbmQgYXNzb2NpYXRlZCBkb2N1bWVudGF0aW9uIGZpbGVzICh0aGUgIlNvZnR3YXJlIiksIHRvIGRlYWwKaW4gdGhlIFNvZnR3YXJlIHdpdGhvdXQgcmVzdHJpY3Rpb24sIGluY2x1ZGluZyB3aXRob3V0IGxpbWl0YXRpb24gdGhlIHJpZ2h0cwp0byB1c2UsIGNvcHksIG1vZGlmeSwgbWVyZ2UsIHB1Ymxpc2gsIGRpc3RyaWJ1dGUsIHN1YmxpY2Vuc2UsIGFuZC9vciBzZWxsCmNvcGllcyBvZiB0aGUgU29mdHdhcmUsIGFuZCB0byBwZXJtaXQgcGVyc29ucyB0byB3aG9tIHRoZSBTb2Z0d2FyZSBpcwpmdXJuaXNoZWQgdG8gZG8gc28sIHN1YmplY3QgdG8gdGhlIGZvbGxvd2luZyBjb25kaXRpb25zOgoKVGhlIGFib3ZlIGNvcHlyaWdodCBub3RpY2UgYW5kIHRoaXMgcGVybWlzc2lvbiBub3RpY2Ugc2hhbGwgYmUgaW5jbHVkZWQgaW4gYWxsCmNvcGllcyBvciBzdWJzdGFudGlhbCBwb3J0aW9ucyBvZiB0aGUgU29mdHdhcmUuCgpUSEUgU09GVFdBUkUgSVMgUFJPVklERUQgIkFTIElTIiwgV0lUSE9VVCBXQVJSQU5UWSBPRiBBTlkgS0lORCwgRVhQUkVTUyBPUgpJTVBMSUVELCBJTkNMVURJTkcgQlVUIE5PVCBMSU1JVEVEIFRPIFRIRSBXQVJSQU5USUVTIE9GIE1FUkNIQU5UQUJJTElUWSwKRklUTkVTUyBGT1IgQSBQQVJUSUNVTEFSIFBVUlBPU0UgQU5EIE5PTklORlJJTkdFTUVOVC4gSU4gTk8gRVZFTlQgU0hBTEwgVEhFCkFVVEhPUlMgT1IgQ09QWVJJR0hUIEhPTERFUlMgQkUgTElBQkxFIEZPUiBBTlkgQ0xBSU0sIERBTUFHRVMgT1IgT1RIRVIKTElBQklMSVRZLCBXSEVUSEVSIElOIEFOIEFDVElPTiBPRiBDT05UUkFDVCwgVE9SVCBPUiBPVEhFUldJU0UsIEFSSVNJTkcgRlJPTSwKT1VUIE9GIE9SIElOIENPTk5FQ1RJT04gV0lUSCBUSEUgU09GVFdBUkUgT1IgVEhFIFVTRSBPUiBPVEhFUiBERUFMSU5HUyBJTiBUSEUKU09GVFdBUkUuCg==",
    "type": "text"
  },
  "vars": {
    "name": {
      "type": "string",
      "description": "The name of the project environment",
      "default": "cas",
      "prompt": "What is the project name?"
    }
  }
});
