---
- name: {{applicationName.sentenceCase()}} {{environment.camelCase()}} site playbook
  hosts: {{applicationName.snakeCase()}}_servers
  become: true
  environment: {{=<% %>=}}"{{ proxy_env }}"<%={{ }}=%>
  tasks:
    - name: Include tasks from file tasks/debug.yml
      ansible.builtin.include_tasks: tasks/debug.yml

    - name: Import role {{organization}}.{{applicationName.snakeCase()}}.install
      ansible.builtin.import_role:
        name: {{organization}}.{{applicationName.snakeCase()}}.install
