---
all:
  hosts:
    gitlab-mgm-production:
      ansible_host: "{{ variable_host | default('viicasmgm001p.vm.cas.kvnbw.net') }}"
      ansible_port: 22022
      ansible_user: ansible
      ansible_ssh_private_key_file: ./ssh/viicasmgm001p_ansible_ed25519
      ansible_python_interpreter: /usr/bin/python3

    # gitlab-runner-1-mgm-production:
    #   ansible_host: "{{ variable_host | default('gitlab-mgmt-runner-1.fritz.box') }}"
    #   ansible_port: 22
    #   ansible_user: ubuntu
    #   ansible_ssh_private_key_file: /home/itag001202/projects/cas-yade/conf/ssh/viicasmgm001p_ansible_ed25519

  children:
    gitlab_servers:
      hosts:
        gitlab-mgm-production:
    # gitlab_runners:
    #   hosts:
    #     gitlab-runner-1-mgm-production:
