version: 3

tasks:
  dart:cleanup:
    cmds:
      - find . -type d -name ".dart_tool" -exec rm -r {} +
      - find . -name "pubspec.lock" -type f -delete
    silent: true

  dart:init:
    cmds:
      - cd ./packages/yade_cli && dart pub get
      - cd ./bricks/create_iac_repo/hooks && dart pub get
    silent: true

  mason:bundle:templates:
    cmds:
      # bundle templates
      - >
        mason bundle \
          -s git git@github.com:abes140377/yade-project-generator-cli \
          --git-path bricks/create_iac_repo \
          -t dart \
          -o packages/yade_cli/lib/src/commands/create/templates
      # format
      - dart format ./packages/yade_cli
    silent: true
