name: yade_cli
description: The official command line interface for YADE. Built by Very Good Ventures.
version: 0.2.0
homepage: https://yade.io
repository: https://github.com/yadeio/yade
issue_tracker: https://github.com/VeryGoodOpenSource/yade/issues
documentation: https://yade.io/docs/overview
topics: [ yade, cli ]

environment:
  sdk: ^3.5.0

dependencies:
  args: ^2.6.0
  cli_completion: ^0.5.1
  dcli: ^6.1.0
  equatable: ^2.0.7
  get_it: ^8.0.2
  http: ^1.2.2
  mason: ^0.1.0
  meta: ^1.16.0
  path: ^1.9.1
  pub_updater: ^0.5.0
  pubspec_parse: ^1.3.0
  settings_yaml: ^8.2.0
  stream_transform: ^2.1.0
  watcher: ^1.1.0
  yaml: ^3.1.2

dev_dependencies:
  build_runner: ^2.4.13
  build_verify: ^3.1.0
  build_version: ^2.1.1
  mocktail: ^1.0.4
  test: ^1.25.9
  very_good_analysis: ^6.0.0

executables:
  yade:
