name: yade_cli
description: The official command line interface for YADE. Built by Very Good Ventures.
version: 1.2.3
homepage: https://yade.io
repository: https://github.com/yadeio/yade
issue_tracker: https://github.com/VeryGoodOpenSource/yade/issues
documentation: https://yade.io/docs/overview
topics: [yade, cli]

#screenshots:
#  - description: 'YADE logo.'
#    path: assets/logo.png

environment:
  sdk: ^3.5.0

dependencies:
  args: ^2.5.0
  cli_completion: ^0.5.1
  equatable: ^2.0.5
  mason: 0.1.0-dev.60
  meta: ^1.15.0
  path: ^1.9.0
  pub_updater: ^0.5.0
  pubspec_parse: ^1.3.0
  stream_transform: ^2.1.0
  uuid: ^4.4.2
  watcher: ^1.1.0

dev_dependencies:
  build_runner: ^2.4.12
  build_verify: ^3.1.0
  build_version: ^2.1.1
  mocktail: ^1.0.4
  test: ^1.25.8
  very_good_analysis: ^6.0.0

executables:
  yade:
