- name: Update and upgrade apt packages
  ansible.builtin.apt:
    upgrade: true
    update_cache: true
    cache_valid_time: 86400 # one day
- name: Check that the reboot-required exists
  ansible.builtin.stat:
    path: /var/run/reboot-required
  register: p
- name: Debug print reboot required
  ansible.builtin.debug:
    msg: "Reboot required"
  when: p.stat.exists

- name: Reboot the server
  ansible.builtin.reboot:
    msg: "Rebooting machine in 5 seconds"
  when: p.stat.exists
