---
all:
  hosts:
    gitlab-mgm-sandbox:
      ansible_host: "{{ variable_host | default('viicasmgm001s.vm.cas.kvnbw.net') }}"
      ansible_port: 22022
      ansible_user: ansible
      ansible_ssh_private_key_file: ./ssh/viicasmgm001s_ansible_ed25519
      ansible_python_interpreter: /usr/bin/python3

    # gitlab-runner-1-mgm-sandbox:
    #   ansible_host: "{{ variable_host | default('gitlab-runner-1-mgmt.fritz.box') }}"
    #   ansible_port: 22
    #   ansible_user: ubuntu
    #   ansible_ssh_private_key_file: /Users/seba/.ssh/ubuntu_ed25519

  children:
    gitlab_servers:
      hosts:
        gitlab-mgm-sandbox:
    # gitlab_runners:
    #   hosts:
    #     gitlab-runner-1-mgm-sandbox:
