---
all:
  hosts:
    {{applicationName}}-mgm-sandbox:
      ansible_host: {{hostname}}s.vm.cas.kvnbw.net
      ansible_port: 22022
      ansible_user: ansible
      ansible_ssh_private_key_file: ./ssh/{{hostname}}s_ansible_ed25519
      ansible_python_interpreter: /usr/bin/python3

    # {{applicationName}}-runner-1-mgm-sandbox:
    #   ansible_host: {{applicationName}}-runner-1-mgmt.fritz.box
    #   ansible_port: 22
    #   ansible_user: ubuntu
    #   ansible_ssh_private_key_file: /Users/seba/.ssh/ubuntu_ed25519

  children:
    {{applicationName}}_servers:
      hosts:
        {{applicationName}}-mgm-sandbox:
    # {{applicationName}}_runners:
    #   hosts:
    #     {{applicationName}}-runner-1-mgm-sandbox:
