collections:
  - name: git@viicasapp003t.intinf.dvvbw.net:itag001202/ansible-collection-cas.git
    type: git
    version: main

  - name: cloud.terraform
    version: 3.0.0
{{#ansibleCollections}}  - name: {{name}}
    version: {{version}}
{{/ansibleCollections}}
roles:
{{#ansibleRoles}}  - name: {{name}}
    version: {{version}}
{{/ansibleRoles}}