- name: Copy ssl certificate to remote host
  ansible.builtin.copy:
    src: files/rz-kiru-root.crt
    dest: /usr/local/share/ca-certificates/rz-kiru-root.crt
    owner: root
    group: root
    mode: '0644'
- name: Update the CA certificates on the remote host
  ansible.builtin.command:
    cmd: update-ca-certificates
  changed_when: true
