- name: Debug multiple variables
  ansible.builtin.debug:
    msg: "Variable {{=<% %>=}}{{ item.name }}: {{ item.value }}<%={{ }}=%>"
  with_items:
    - { name: "env", value: "{{=<% %>=}}{{ env }}<%={{ }}=%>" } # check var from inventory/host_vars/{{applicationName.camelCase()}}-{{environment.camelCase()}}-<env>.yml
