---
all:
  hosts:
    {{applicationName}}-mgm-labor:
      ansible_host: {{hostname}}l.vm.cas.kvnbw.net
      ansible_port: 22022
      ansible_user: ansible
      ansible_ssh_private_key_file: ./ssh/{{hostname}}l_ansible_ed25519
      ansible_python_interpreter: /usr/bin/python3

    # {{applicationName}}-runner-1-mgm-labor:
    #   ansible_host: {{applicationName}}-mgmt-runner-1.fritz.box
    #   ansible_port: 22
    #   ansible_user: ubuntu
    #   ansible_ssh_private_key_file: /home/itag001202/projects/cas-yade/conf/ssh/viicasmgm001s_ansible_ed25519

  children:
    {{applicationName}}_servers:
      hosts:
        {{applicationName}}-mgm-labor:
    # {{applicationName}}_runners:
    #   hosts:
    #     {{applicationName}}-runner-1-mgm-labor:
